services:
  - type: web
    name: hd-monks-api
    runtime: python
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    buildCommand: "cd backend && pip install -r requirements.txt"
